<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
<title>The Home Page of The Matt&trade;</title>
<link href="default.css" rel="stylesheet" type="text/css" />
</head>

<body>
<div id="wrapper">
  <div id="header"><img src="gfx/header1.jpg" alt="The Home Page of The Matt&trade;" width="800" height="120" /></div>
  <div id="menu"><a href="#">about me</a>&nbsp;&nbsp; <a href="#">Downloads</a>&nbsp;&nbsp; <a href="#">forums</a>&nbsp;&nbsp; <a href="#">games</a>&nbsp;&nbsp; <a href="#">guestbook</a>&nbsp;&nbsp;<a href="#">links</a>&nbsp;&nbsp; <a href="#">Photo Gallery</a>&nbsp;&nbsp; <a href="#">main</a>&nbsp;&nbsp; </div>
  <div id="content">
    <p>Welcome to the home page of the matt&trade;. feel free to look around. be sure to check out my links while you are here.</p>
    <p>The matt&trade;  </p>
  </div>
  <div id="footer"><!-- Generated by www.webweaver.nu -->
<script language="JavaScript">
<!--
document.write('&copy;' );
document.write(' 2006 - ');
document.write(new Date().getFullYear());
document.write(' The Home Page of The Matt™ - Whizkid Online - All Rights Reserved.');
//-->
</script> | Licensed Under the MIT License, source at <a href="http://github.com/mattburchett/oldsites">GitHub</a> <br />
<a href="http://www.punbb.org"><img src="gfx/bt-punbb.gif" alt="Powered By PunBB" width="80" height="15" border="0" /></a>&nbsp;&nbsp; <img src="gfx/viper.gif" alt="Powered By ViPER Guestbook" width="80" height="15" />&nbsp;&nbsp; <a href="http://coppermine-gallery.net/"><img src="gfx/coppermine.gif" alt="Powered By Coppermine Photo Gallery" width="80" height="15" border="0" /></a>&nbsp;&nbsp; <a href="http://www.mozilla.com"><img src="gfx/get_firefox.png" alt="Get Firefox!!" width="80" height="15" border="0" /></a>&nbsp;&nbsp; <a href="http://www.opera.com"><img src="gfx/opera.png" alt="Opera Browser Supported" width="80" height="15" border="0" /></a>&nbsp;&nbsp; <a href="http://www.avantbrowser.com"><img src="gfx/avant.gif" alt="Avant Browser Supported" width="80" height="15" border="0" /></a>&nbsp;&nbsp; <a href="http://www.maxthon.com"><img src="gfx/maxthon.gif" alt="Maxthon Browser Supported" width="80" height="15" border="0" /></a>&nbsp;&nbsp; <img src="gfx/w3c-css.gif" alt="CSS Verified" width="80" height="15" />&nbsp;&nbsp; <img src="gfx/w3c-xhtml.gif" alt="XHTML Verified" width="80" height="15" /></div>
</div>
</body>
</html>
